### ISSUE TITLE
 Cannot read property 'DocumentDir' of undefined

### ISSUE THREAD

**Issue by ZSH-HSZ** [Jancat/react-native-slide-verify#1]
本地已经连接了 react-native-vector-icons
rn版本0.50.0

**Comment by Jancat** [comment]
该库没有使用到 `DocumentDir` 这个属性，可否贴下错误截图？

**Comment by ZSH-HSZ** [comment]
这样的报错，我用了其他的库，晚上拿项目给你截图

**Comment by robiadiprawira** [comment]
i have same issue, can u people using english please ....  ?

**Comment by Jancat** [comment]
@robiadiprawira Please provide more error info.

**Comment by robiadiprawira** [comment]
@Jancat 
i m new using this library,  i found this kind of error ... 
![whatsapp image 2018-07-11 at 13 45 32](https://user-images.githubusercontent.com/40000853/42555040-31920836-8511-11e8-98bd-076f1c154c93.jpeg)

**Comment by Jancat** [comment]
@robiadiprawira It seems to resolve images path failed. Maybe related to Windows file path separator.

You can copy the library main [file](https://github.com/Jancat/react-native-slide-verify/blob/master/src/SlideVerify/index.js) to your local project to debug.
